---
title: "draft 1"
author: "Ping"
date: "1/27/2021"
output: html_document
---
```{r}
library(fivethirtyeight)
library(fivethirtyeightdata)
library(dplyr)
library(tidyverse)
```


Import datasets
```{r}
ggtrends<-google_trends
tvstates<-tv_states

```

```{r}
ggtrends_longer<-ggtrends %>% 
  pivot_longer("hurricane_harvey_us" : "hurricane_jose_us",
               names_to = "hurricane",
               values_to = "coverage")
```


Plot1 draft
```{r}
ggplot(ggtrends_longer, aes(date, coverage))+
  geom_line(aes(color = hurricane))
```


Plot1 polished
```{r}
ggplot(ggtrends_longer, aes(date, coverage))+
  geom_line(aes(fill = hurricane), color = "white") + 
  geom_ribbon(aes(ymin = 0, ymax = coverage, fill = hurricane), alpha  = 0.5)+
  theme_minimal()+
  labs(title = "News Coverage about Hurricanes in the US on Google Trends", subtitle = "From August to September 2017", x = "Date", y = "Numbers of news coverage", caption = "Data source: fivethrityetight")+
  scale_fill_discrete(name = "Hurricane", labels = c("Harvey", "Irma", "Jose", "Maria"))
```

Plot2

```{r}
ggplot(ggtrends_longer, aes(date, hurricane))+
  geom_tile(aes(fill = coverage),
            color = "white")+
  coord_fixed()+
  scale_fill_viridis_c(option = "magma")+
  theme(axis.ticks.y = element_blank()) +
  scale_y_discrete(labels = c("Harvey", "Irma", "Jose", "Maria"))+
  labs(X = "Date", Y = "Hurricane")
```

Create a data frame. The hurricanes made landfall on (approximately) the following days:

    Harvey: August 25, 2017
    Irma: September 10, 2017
    Jose: Did not make landfall
    Maria: September 20, 2017
    

```{r}
date_landfall <-c("2017-08-25", "2017-09-10", "NA", "2017-09-20")
df <-tibble(
  date_landfall,hurricane = c("Harvey", "Irma", "Jose", "Maria"))
df$date_landfall = as.Date(df$date_landfall)

```



Annotate Plot1 to include the reference points with vertical lines
```{r}
ggplot(ggtrends_longer, aes(date, coverage))+
  geom_line(aes(fill = hurricane), color = "white") + 
  geom_ribbon(aes(ymin = 0, ymax = coverage, fill = hurricane), alpha  = 0.5)+
  theme_minimal()+
  labs(title = "News Coverage about Hurricanes in the US on Google Trends", subtitle = "From August to September 2017", x = "Date", y = "Numbers of news coverage", caption = "Data source: fivethrityetight")+
  scale_fill_discrete(name = "Hurricane", labels = c("Harvey", "Irma", "Jose", "Maria"))+
  geom_vline(data =df, aes(xintercept = date_landfall), color = "grey66", linetype = "dotted", size = 1, alpha = 1)


```


